### ISSUE TITLE
Dockerfile for controller should not need golang as base

### ISSUE THREAD

**Issue by fzxu** [intuit/katlas#133]
The way the current k8s collector (https://github.com/intuit/katlas/blob/master/controller/Dockerfile) runs in the image is not ideal, it should be compiled in prior and put in the alpine base image. 

ref: https://github.com/intuit/katlas/blob/master/service/Dockerfile

**Comment by Lucy911** [comment]
Created Makefile and modified Dockerfile with alpine base image. 
Need to test the changes on Kubenetes minikube.

**Comment by Lucy911** [comment]
Testing is done. PR submitted.

**Comment by Lucy911** [comment]
Done
