### ISSUE TITLE
Graph view requesting `undefined` entity UID

### ISSUE THREAD

**Issue by davemasselink** [intuit/katlas#78]
Once the user loads the graph view, an async request is made to retrieve entity data by UID. The UI is currently requesting `undefined` value from the API. This likely means that a recent change caused an issue where the root node UID is not being correctly registered and maintained.

Here is an example API request URI: https://example.com/v1/entity/uid/undefined

The user experience of this bug is that the orange notifier banner appears and indicates the following error: "rpc error: code = Unknown desc = Some variables are used but not defined Defined:[] Used:[undefined]"

I am seeing this behavior in all deployed environments.

**Comment by davemasselink** [comment]
@fzxu, I suspect this could stem from some of the changes recently made to the use of redux actions in terms of registering a root entity's UID, which the UI will then periodically request

**Comment by fzxu** [comment]
https://github.com/intuit/katlas/pull/80
