### ISSUE TITLE
UI mockup for change history

### ISSUE THREAD

**Issue by fzxu** [intuit/katlas#96]
Design the mockup for object change history

**Comment by davemasselink** [comment]
[KAtlasHistorical.pdf](https://github.com/intuit/katlas/files/2916409/KAtlasHistorical.pdf)

**Comment by fzxu** [comment]
make the select symbol a little bit bigger is not obvious. Would have a different colored circle around it, or having a check mark symbol on top of it/beside it to make it more obvious that is the selected one?

**Comment by davemasselink** [comment]
good suggestions, thanks... I'll iterate and ping you when updated so you can take a look

**Comment by davemasselink** [comment]
@fzxu, updated mock-ups: 
[KAtlasHistorical.pdf](https://github.com/intuit/katlas/files/2937519/KAtlasHistorical.pdf)

**Comment by fzxu** [comment]
looks good to me.

**Comment by davemasselink** [comment]
will close this issue for now; will share updates with teammates who may not have seen them at next katlas team sprint demos

**Comment by davemasselink** [comment]
Received some in-person feedback from @dwding18 about the current mock-ups.

I will re-open this issue to:
* add time ticks and labels on horiz time bar
* compare states: just successive history items; remove check boxes and function of comparing 2 arbitrary states
* make details panel hide-able? or leave this to #140?

**Comment by davemasselink** [comment]
Made updates based on @dwding18's notes earlier this week. I only made updates showing the first 2 bullet points in my last note, leaving the hidden details panel as a part of issue #140.

[KAtlasHistorical.pdf](https://github.com/intuit/katlas/files/2973254/KAtlasHistorical.pdf)

**Comment by davemasselink** [comment]
We will have a design mtg to go over most recent mock-up changes during this week.
